- name: Dev | install node
  become: yes
  zypper:
    name: nodejs10
    state: present

- name: Dev | import Microsofot keys
  rpm_key:
    state: present
    key: "https://packages.microsoft.com/keys/microsoft.asc"

- name: Dev | add VSCode repo
  become: yes
  copy:
    src: vscode.repo
    dest: "/etc/zypp/repos.d/vscode.repo"

- name: Dev | install Visual Studio Code
  become: yes
  zypper:
    name: code
    state: present
    update_cache: yes
