---
- name: Mozilla | add repos
  become: "yes"
  zypper_repository:
    repo: "http://download.opensuse.org/repositories/mozilla/openSUSE_Tumbleweed/"
    name: "mozilla"
    auto_import_keys: "yes"
