---
- name: Docker | Install Docker
  zypper: docker
  status: present
  become: yes

- name: Docker | Install Docker Compose
  zypper: docker-compose
  status: present
  become: yes
    
- name: Docker | Enable Docker daemon
  command: systemctl enable docker
  become: yes

- name: Docker | Add current user to docker group
  user: name={{ deploy_user }} groups=docker append=yes
  become: yes